esphome:
  name: livingroom
  platform: ESP32
  board: esp32doit-devkit-v1

switch:
  - platform: gpio
    name: "Living Room Lights"
    pin: 19

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password