esphome:
  name: single_switch_1
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#api:

logger:

ota:
  password: !secret ota_password

web_server: 
  port: 80

mqtt:
  broker: !secret mqtt_broker
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  port: !secret mqtt_port
  # Set to true when finished testing to set MQTT retain flag
  discovery_retain: false
  birth_message:
    topic: single_switch_1/status
    payload: online
  will_message:
    topic: single_switch_1/status
    payload: offline

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    #name: "Sonoff Basic Button" # We don't need to see the button state in the GUI.
    id: sonoff_button
    on_press:
      - switch.toggle: relay

switch: #mqtt topic: single_switch_1/switch/sonoff_basic_relay/state
  - platform: restart
    name: "Switch 1 Device Restart"
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
  