build: 
	docker build -t home_node_server:latest .
run: 
	#docker run -it -e "NODE_RED_CREDENTIAL_SECRET=your_secret_goes_here" -p 1880:1880 -v `pwd`/node-red:/data --name current_node_image home_node_server
	docker-compose up

